### ISSUE TITLE
Unable to close jane from a php document

### ISSUE THREAD

**Issue by Xavier74** [qtnc/jane#2]
Hello,

When a php document is opened in jane, it is not possible to close the app. None of shortcut works, e.g. pressing alt does not go to menu, alt+f4 does not close the app. I need to switch to jaws cursor to manually click on the file menu to have access to close option.
i don't get this problem with other file extension, only .php.
if i rename my test.txt file (which its working) to test.php, when i open it i cannot close the app.

I'm using windows 10 pro 64bits.

**Comment by qtnc** [comment]
Hello,

I don't observe the problem or can't reproduce it. Have you tried 
directly from source ?

I have made a new 32-bit build today, perhaps it solves this issue.
http://vrac.quentinc.net/Jane-0.0.zip

**Comment by Xavier74** [comment]
yes, this new version works fine.
Replacing old file with new one has not solved the problem, but deleting them and installed your proposed version files has worked.
Hope you have understanded the reason of this.

Many thanks !

**Comment by qtnc** [comment]
No problem, you're welcome.

Issue fixed
Close #2
